config/routes.rb
Rails.application.routes.draw do
  get 'flight_ride/new'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#new'
  get 'flights/index'
  get '/signin' => "sessions#create"
  get '/login'  => "sessions#new"
  post '/sessions' => "sessions#create"
  post 'flights/new' => "flights#create"
  delete '/logout' => "sessions#destroy"

  patch '/login', to: 'sessions#create'

  get 'flights/:id/flight_data', to: 'flights#flight_data'

  get '/users' => "users#new"
  get '/auth/facebook/callback' => 'sessions#create'
 
   resources :users, :only => [:new, :create, :show]
   resources :flights, only: [:index, :show, :new, :create, :edit, :update]  # access to all the functions.
   
  #  post '/flight_ride/new' => "flight_ride#new" 

   # this is the code you need
    resources :users do
      resources :flight_rides, only: [:index, :show, :new, :create, :edit, :update, :destroy] # reduce the actions to what you only need
     end
  
    # resources :flight_rides, only:[:index]
# make Commercial . Not restful Flight +
   
    get 'commercial' => 'flights#commercial'
 end

app/models/flight_ride.rb
class FlightRide < ApplicationRecord
    belongs_to :user
    belongs_to :flight


    def take_flight


                if  self.user.user_cash > self.flight.fuel_cost && self.flight.inspection == "true" 
                        
                
                       new_cash = self.user.user_cash - self.flight.fuel_cost
                        self.user.update(:user_cash => new_cash)
            
                        self.user.save
                        "Thanks for riding this flight #{self.user.name}!"

                elsif self.user.user_cash > self.flight.fuel_cost && self.flight.inspection == "false" 
                    "Sorry for the inconvenience, This flight did not pass inspection #{self.user.name}"
                else
                        "Sorry. You dont have enough money flight for your trip #{self.user.name}."
                    
                 end

    end
      

end

app/controllers/flight_rides_controller.rb
class FlightRidesController < ApplicationController

        skip_before_action :verify_authenticity_token
      
        def index

          if params[:user_id] 
            @user = User.find_by_id(params[:user_id])
               
            if @user 
               @flight_rides = @user.flight_rides

            else
               redirect_to users_path
            end
         else
         
            @flight_rides = FlightRide.all

          end
   
        end
      
        def new
         @flight_ride = FlightRide.create(flight_ride_params)

         flash[:notice] = @flight_ride.take_flight

         redirect_to user_path(@flight_ride.user) # this should feed into user id with an updated ticekts and stuff.
        end
      
         def create
            @user = User.find(params[:user_id]) 
            @flight_ride = @user.flight_rides.build(flight_ride_params)
           if @flight_ride.save
             redirect_to user_flight_rides_path(@user)
         
           else
           render "users/show"
           end
         end

          def edit
               if logged_in?
                  @flight_ride = FlightRide.find(params[:id])
                  redirect_to user_flight_ride_path(current_user)
               else
                 render 'flights/new'
               end
            
          end
      
      
         def update
            @flight_ride = FlightRide.find(params[:id])
            @flight_ride.update(flight_ride_params)
    
            redirect_to user_path(@flight_ride.user)
         end
        
         def show
            @flight_ride = FlightRide.find(params[:id])
            redirect_to 'flight_rides/show'

         end

         def destroy
            @flight_ride = FlightRide.find(params[:id])
          
            @flight_ride.delete
            redirect_to user_flight_rides_path(session[:user_id])

         end

      

         private

      def flight_ride_params
         params.require(:flight_ride).permit(:user_id, :flight_id, :flight_class)
      end 

      
      
end

app/helpers/flight_rides_helper.rb
module FlightRidesHelper
end

app/views/flight_rides/edit.html.erb
<section class="jet">
  <header class="header">
    <h1>Edit Flight_ride</h1>

<%= form_for @flight_rides, :url => user_flight_rides_path(current_user) do |f| %>
       <%= f.label :inspection %>
       <%= f.check_box :inspection %>  <br />

       <%= f.label :fuel_cost %>
        <%= f.text_field :fuel_cost %><br />

        <%= f.label :destination %>
        <%= f.text_field :destination %><br />

        <%= f.label :flight_departure %>
        <%= f.text_field :flight_departure %><br />

          <%= f.label :flight_sit %>
        <%= f.text_field :flight_sit %><br />

        <%= f.select :flight_class, ['Economy', 'Coach', 'First_class']%> 

    
        <br>
        <%= f.submit%>
        <% end %>
      </form>

  </header>
  
</section>

app/views/flight_rides/index.html.erb
       <h3>Flight_ride Information</h3>

 <% @flight_rides.each do |flight_ride| %>
    <div>
     <h2><%= flight_ride.id %></h2>
  
     <h3>by: <%= link_to flight_ride.user.name, user_path(flight_ride.user_id) %></h3>
     <p><%= flight_ride.flight_class %></p>
   </div>
<% end %>

  <%= hidden_field_tag :user_id, current_user.id %>

  <%= hidden_field_tag :name => request_forgery_protection_token.to_s, :value => form_authenticity_token %>
   

     <p><%= link_to "Create a New flight", new_flight_path %></p>

     <%=link_to "Log Out", logout_path, :method => :delete %>
     <%= hidden_field_tag :user_id, current_user.id %>

app/views/flight_rides/show.html.erb
<p> Shows all flight_Ride</p>

 <p> This is the users show page, List result or tickets after the went on the ride</p>
 <header class="header">
    
    User: <p><%= @user.name %><br></p>
    <br>
    <h4> Flight_Ride Iternary</h4>
   <br>
   
    <% @user.flight_rides.each do |user_flight_ride|%>
     <br>
     <p>flight_ride_id</p>
     <p> <%= user_flight_ride.id%></p>

     <p>flight_class</p>
     <p> <%= user_flight_ride.flight_class%></p>

     <p>flight_id </p>
     <p> <%= user_flight_ride.flight_id%></p>
<br>

<br>
   <p><%= link_to "Delete This Flight", user_flight_ride_path(current_user) %></p>
    <%end%>

  <br>
      <h2><%= link_to "See all Flights", flights_path %></h2>

        <% if flash[:notice] %>
       <div class="notice"><%= flash[:notice] %></div>
        <% end %>
   <br>
    
   <br>

     <%=link_to "Log Out", logout_path, :method => :delete %>
        <%= hidden_field_tag :user_id, current_user.id %>
  <br>
   OR
  <br>

        <% if auth_hash = request.env["omniauth.auth"] %>
        <h1><%= @user.name %></h1>
        <h2>Email: <%= @user.email %></h2>
        <h2>Facebook UID: <%= @user.uid %></h2>
        <img src="<%= @user.image %>">
        <% else %>
        <%= link_to('Log in with Facebook!', '/auth/facebook') %>
        <% end %>

  </header>

  