config/routes.rb
Rails.application.routes.draw do
  get 'flight_ride/new'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#new'
  get 'flights/index'
  get '/signin' => "sessions#create"
  get '/login'  => "sessions#new"
  post '/sessions' => "sessions#create"
  post 'flights/new' => "flights#create"
  delete '/logout' => "sessions#destroy"

  patch '/login', to: 'sessions#create'

  get 'flights/:id/flight_data', to: 'flights#flight_data'

  get '/users' => "users#new"
  get '/auth/facebook/callback' => 'sessions#create'
 
   resources :users, :only => [:new, :create, :show]
   resources :flights, only: [:index, :show, :new, :create, :edit, :update]  # access to all the functions.
   
  #  post '/flight_ride/new' => "flight_ride#new" 

   # this is the code you need
    resources :users do
      resources :flight_rides, only: [:index, :show, :new, :create, :edit, :update, :destroy] # reduce the actions to what you only need
     end
  
    # resources :flight_rides, only:[:index]
# make Commercial . Not restful Flight +
   
    get 'commercial' => 'flights#commercial'
 end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :flight_rides
	has_many :flight,through: :flight_rides


	validates :name, presence: true
	validates :name, uniqueness:  true

	validates :name, format: {without: /[0-9]/, message: "does not allow numbers" }
	validates :password, presence: true

	def self.find_or_create_by_omniauth(auth_hash)
        self.where(:name => auth_hash[:info][:name]).first_or_create do |user|
			user.password = SecureRandom.hex
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @user = User.new
  end

 def create  
  @user = User.new(user_params)

  if @user.valid?
    @user.save
    session[:user_id] = @user.id  #attempt to log them in.
    
    redirect_to flights_path
   else

    render 'sessions/login' 
    
   end
  end

   def show
    if !session.include?(:user_id)
      redirect_to root_path
    else
    @user = User.find(params[:id])
    # render 'users/show'

     #  using Json
     respond_to do |f|
      f.html {render :show}
      f.json {render json:@user}
      # render json: @user, status: 200
     end
    end
  end

  
  
   private

   def auth
    request.env['omniauth.auth']
    end


  def user_params
    params.require(:user).permit(:name, :user_cash, :password)
  end 


end # class end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<section class="jet">
  <header class="header">

    <h1>SignUp</h1>
    <%= form_for(@user) do |f| %>
   <br>
       <%= f.label :name %>
       <%= f.text_field :name %>
       <br />
       <br>
      
        <%= f.label :password %>
        <%= f.text_field :password %>
        <br />       <br>
        <%= f.submit "Sign Up", data: {disable_with: false}%>

        <br>
        <% end %>
      </form>
 
   <br>
   <br>
      <%= link_to('Login with Facebook', '/auth/facebook') %>

  </header>
  
</section>

app/views/users/show.html.erb
<header class="header">
    
    <h4>User</h4>
    <p><%= @user.name %></p>

  <br>
     <h2><%= link_to "See all Flights", flights_path, class: "all_flights" %></h2>
</header>
        <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
         <% end %>
  
    <br>
    <h4> FlightRides</h4>

    <% @user.flight_rides.each do |user_flight_ride|%>
     <br>
     <h4>flight_ride_id</h4>
     <p> <%= user_flight_ride.id%></p>

      <h4>flight_class</h4>
      <p> <%= user_flight_ride.flight_class%></p>

      <h4>flight_id </h4>
      <p> <%= user_flight_ride.flight_id%></p>

      <h4><%= link_to "Delete This Flight", user_flight_ride_path(current_user, user_flight_ride), :method => :delete%></h4>
      <br>
    <%end%>

     <%=link_to "Log Out", logout_path, :method => :delete %>
     <%= hidden_field_tag :user_id, current_user.id %>
      <br>

        <% if auth_hash = request.env["omniauth.auth"] %>
        <h1><%= @user.name %></h1>
        <h2>Email: <%= @user.email %></h2>
        <h2>Facebook UID: <%= @user.uid %></h2>
        <img src="<%= @user.image %>">
        <% else %>
        <%= link_to('Log in with Facebook!', '/auth/facebook') %>
        <% end %>

  </header>

  
    